routes/admin.php
<?php

/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
|
| Here is where you can register admin routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "admin" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Route;

Route::get('/', 'DashboardController@index')->name('dashboard');

Route::prefix('contact')->name('contact.')->group(function () {
    Route::get('/', 'ContactController@index')->name('index');
    Route::post('/', 'ContactController@send')->name('send');
});

Route::match([  'get', 'post'], 'promotions', 'PromotionsPageController@index')->name('promotions');

Route::resource('users', 'UserController')->only('edit', 'update');

Route::resource('businesses', 'BusinessController')->only('index', 'edit', 'update');
Route::resource('locations', 'LocationController')->only('index', 'edit', 'update');

Route::prefix('locations')->name('locations.')->group(function () {
    Route::get('payment/{payment_id?}', 'LocationController@index');
    Route::get('{hash}/address', 'LocationController@editAddress')->name('address');
    Route::put('{hash}/address', 'LocationController@updateAddress')->name('update-address');
    Route::get('{hash}/hours', 'LocationController@editHours')->name('hours');
    Route::put('{hash}/hours', 'LocationController@updateHours')->name('update-hours');
    Route::get('{hash}/images', 'LocationController@editImages')->name('images');
    Route::put('{hash}/images', 'LocationController@updateImages')->name('update-images');
    Route::get('{hash}/texts', 'LocationController@editTexts')->name('texts');
    Route::put('{hash}/texts', 'LocationController@updateTexts')->name('update-texts');
    Route::delete('{hash}/images/{file_id}/destroy', 'LocationController@destroyImage')->name('destroy-image');
    Route::delete('{hash}/destroy', 'LocationController@destroy')->name('destroy');
});

Route::view('invoices', 'admin.invoices.index')->name('invoices.index');
Route::get('invoices/download/{order_id}', function ($orderId) {
    return request()->user()->downloadInvoice($orderId);
})->name('invoices.download');

Route::prefix('reviews')->name('reviews.')->group(function () {
    Route::get('{location?}', 'ReviewController@index')->name('index');
    Route::delete('{review}', 'ReviewController@destroy')->name('destroy');
    Route::post('{review}/report', 'ReviewController@report')->name('report');
    Route::get('{review}/responses/create', 'ReviewController@createResponse')->name('responses.create');
    Route::get('{review}/responses/{response}', 'ReviewController@editResponse')->name('responses.edit');
    Route::put('{review}/responses/{response}', 'ReviewController@updateResponse')->name('responses.update');
    Route::post('{review}/responses', 'ReviewController@storeResponse')->name('responses.store');
});

Route::prefix('questions')->name('questions.')->group(function () {
    Route::get('{location?}', 'QuestionController@index')->name('index');
    Route::delete('{question}', 'QuestionController@destroy')->name('destroy');
    Route::post('verified', 'QuestionController@verifiedFAQ')->name('verified-faq');
    Route::post('{question}/report', 'QuestionController@report')->name('report');
    Route::get('{question}/answers', 'AnswerController@index')->name('answers.index');
    Route::post('{question}/answers', 'AnswerController@store')->name('answers.store');
    Route::get('{question}/answers/create', 'AnswerController@create')->name('answers.create');
    Route::put('{question}/answers/{answer}', 'AnswerController@update')->name('answers.update');
    Route::delete('{question}/answers/{answer}', 'AnswerController@destroy')->name('answers.destroy');
    Route::get('{question}/answers/{answer}/edit', 'AnswerController@edit')->name('answers.edit');
    Route::post('{question}/answers/{answer}/report', 'AnswerController@report')->name('answers.report');
});

Route::prefix('location-wizard')->name('location-wizard.')->group(function () {
    Route::get('/', 'LocationWizardController@index')->name('index');
    Route::post('/', 'LocationWizardController@saveProgress')->name('save-progress');
    Route::post('destroy', 'LocationWizardController@destroyProgress')->name('destroy-progress');
    Route::get('add-location', 'LocationWizardController@addLocation')->name('add-location');
    Route::get('load-businesses', 'LocationWizardController@loadBusinesses')->name('load-businesses');
    Route::get('load-locations', 'LocationWizardController@loadLocations')->name('load-locations');
    Route::get('load-holidays', 'LocationWizardController@loadHolidays')->name('load-holidays');
    Route::get('load-categories', 'LocationWizardController@loadCategories')->name('load-categories');
    Route::get('resolve-address', 'LocationWizardController@resolveAddress')->name('resolve-address');
    Route::post('store', 'LocationWizardController@store')->name('store');
});

// scraper
Route::post('scraper', 'WebsiteScraperController')->name('scraper');

// Subscription
Route::match(['get', 'post'], 'subscribe/{hash?}', 'SubscriptionController@subscribe')->name('subscribe');
Route::post('validate-coupon', 'SubscriptionController@validateCoupon')->name('validate-coupon');

// changeLocale
Route::get('country/{code}', 'DashboardController@changeCountry')->name('change-country');
Route::get('locale/{code}', 'DashboardController@changeLocale')->name('change-locale');

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Models\Order;
use App\Models\Subscription;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use Laravel\Cashier\Coupon\RedeemedCoupon;
use Laravel\Cashier\Credit\Credit;
use Laravel\Cashier\Order\OrderItem;

Auth::routes(['verify' => true]);

Route::get('/', function () {
    return redirect()->intended(route('admin.locations.index'));
});

// Cache bust route
Route::get('cache-bust', function (Request $request) {
    if ($userId = $request->input('deleted_user_id')) {
        Subscription::query()->where('owner_type', User::class)->where('owner_id', $userId)->delete();
        Order::query()->where('owner_type', User::class)->where('owner_id', $userId)->delete();
        OrderItem::query()->where('owner_type', User::class)->where('owner_id', $userId)->delete();
        RedeemedCoupon::query()->where('owner_type', User::class)->where('owner_id', $userId)->delete();
        Credit::query()->where('owner_type', User::class)->where('owner_id', $userId)->delete();
    }

    Artisan::call('cache:clear');
});

// Mollie webhooks
Route::prefix('webhooks')->group(function () {
    Route::prefix('mollie')->group(function () {
        Route::get('/', 'MollieController@index');
        Route::get('first-payment', 'MollieController@index');
    });
});

app/Models/Location.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Location extends Model
{
    protected $connection = 'mysql_backend';
    protected $table      = 'published_locations';

    const SOURCE_YEXT = 'yext';
}

app/Http/Controllers/Admin/LocationController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\AppliedCoupon;
use App\Models\Coupon;
use App\Models\LocationWizard;
use App\Models\Subscription;
use App\Models\User;
use App\Services\AdminHoursService;
use App\Services\LocationImporter;
use App\Services\WizardService;
use Exception;
use Honeybadger\HoneybadgerLaravel\Facades\Honeybadger;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Cookie;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Validator;
use Illuminate\Validation\ValidationException;
use Laravel\Cashier\Order\Order;
use Laravel\Cashier\Payment;
use Symfony\Component\HttpKernel\Exception\HttpException;

class LocationController extends Controller
{
    protected AdminHoursService $adminHoursService;
    protected LocationImporter $locationImportService;

    public function __construct(AdminHoursService $adminHoursService, LocationImporter $locationImportService)
    {
        $this->adminHoursService = $adminHoursService;
        $this->locationImportService = $locationImportService;
    }

    public function index(Request $request, string $paymentId = null)
    {
        /** @var User $user */
        $user = $request->user();

        Cookie::queue(
            Cookie::forget('wizard_id')
        );

        $locations = $user->locations()->groupBy('business.name');

        if ($locations->isEmpty()) {
            return redirect(route('admin.location-wizard.index'));
        }

        if ($paymentId && ($payment = Payment::findByPaymentId($paymentId))) {
            $order = $payment->order;

            $orderable = $order?->items()?->where('orderable_type', Subscription::class)?->first()?->orderable ?? null;

            /** @var ?Subscription $subscription */
            $subscription = match (true) {
                $orderable instanceof Subscription => $orderable,
                $orderable instanceof AppliedCoupon => $orderable->model,
                default => null,
            };

            [, $hash] = explode(';', $subscription->name ?? ';');

            if ($hash) {
                $this->adminHoursService->promoteLocation(['hash' => $hash]);
            }

            if ($subscription) {
                flash(__('dashboard.promotion_success_message'))->success();
                $messageArray = ['success' => __('dashboard.promotion_success_message')];

                if ($subscription instanceof Subscription) {
                    foreach ($subscription->redeemedCoupons()->pluck('name')->toArray() as $couponCode) {
                        Coupon::query()->where('code', $couponCode)->increment('usage_counter');
                    }
                }
            } else {
                flash(__('dashboard.promotion_error_message'))->error();
                $messageArray = ['error' => __('dashboard.promotion_error_message')];
                Log::error('Promotion error', [
                    'payment_id' => $paymentId,
                    'orderable' => $orderable,
                ]);
            }

            $request->session()->remove('hashes');
        }

        return view('admin.locations.index', [
            'items' => $locations
        ])->with($messageArray ?? []);
    }

    public function edit(Request $request, string $hash)
    {
        $location = $request->user()->locations()->firstWhere('hash', $hash);

        if (!$location) {
            abort(404);
        }

        $wizard = LocationWizard::fromHash($location->hash);

        return view('admin.locations.edit-all', [
            'item' => $location,
            'wizard' => $wizard,
            'isPartOfChain' => $location->business->is_chain ?? 0,
            'step3' => optional($wizard)->data['step3'] ?? [],
            'times' => optional($wizard)->data['step3']['times'],
            'address' => (array)$location->address ?? [],
            'contact' => (array)$location->meta_schema ?? []
        ]);
    }

    public function editAddress(Request $request, string $hash)
    {
        $location = $request->user()->getLocation($hash);

        if (!$location) {
            Auth::logout();
            return redirect(route('login'));
        }

        return view('admin.locations.address', [
            'item' => $location,
            'address' => (array)$location->address ?? [],
            'contact' => (array)$location->meta_schema ?? [],
            'showLocalFields' => request()->user()->isAdmin() || ($location->business->is_chain ?? 0),
        ]);
    }

    public function editHours(Request $request, string $hash)
    {
        $location = $request->user()->getLocation($hash);

        if (!$location) {
            Auth::logout();
            return redirect(route('login'));
        }

        $locationArray = json_decode(json_encode($location), true) ?: [];

        $wizard = $request->user()->locations()->firstWhere('hash', $hash) ?
            LocationWizard::fromHash($location->hash) :
            $this->locationImportService->instantiateWizardFromLocation($locationArray);

        $step3 = $wizard->data['step3'] ?? [];

        return view('admin.locations.hours', [
            'item' => $location,
            'step3' => $step3,
            'times' => $step3['times'] ?? [],
        ]);
    }

    public function editImages(Request $request, string $hash)
    {
        $location = $request->user()->getLocation($hash);

        if (!$location) {
            Auth::logout();
            return redirect(route('login'));
        }

        return view('admin.locations.images', [
            'item' => $location,
            'images' => (array)$location->location_hash->files ?? [],
        ]);
    }

    public function editTexts(Request $request, string $hash)
    {
        $location = $request->user()->getLocation($hash);

        if (!$location) {
            Auth::logout();
            return redirect(route('login'));
        }

        $texts = $location->location_hash->texts ?? [];
        $description = array_filter($texts, fn($text) => $text->slug->slug === 'promoted-description');

        return view('admin.locations.texts', [
            'item' => $location,
            'description' => $description[0] ?? null,
        ]);
    }

    public function editReviews(Request $request, string $hash)
    {
        return $this->editAddress($request, $hash);
    }

    public function editQa(Request $request, string $hash)
    {
        return $this->editAddress($request, $hash);
    }

    public function update(Request $request, string $hash)
    {
        $location = $request->user()->getLocation($hash);

        if (!$location) {
            Auth::logout();
            return redirect(route('login'));
        }

        $locationArray = json_decode(json_encode($location), true) ?: [];
        $newAddressId = $request->input('step2.new_location.address.address_id');
        $hasDifferentAddress = $newAddressId && (intval($location->address->id) !== intval($newAddressId));
        $redirectFromHash = $hasDifferentAddress ? $location->hash : null;
        $ownLocation = $request->user()->locations()->firstWhere('hash', $hash);

        $validator = Validator::make(
            $request->all(),
            [
                'step2.new_location.email' => ['sometimes', 'nullable', 'email'],
                'step2.new_location.phone' => ['sometimes', 'nullable', 'digits_between:6,15'],
                'step2.new_location.fax' => ['sometimes', 'nullable', 'digits_between:6,15'],
            ], [],
            [
                'step2.new_location.email' => 'email',
                'step2.new_location.phone' => 'phone',
                'step2.new_location.fax' => 'fax',
            ]
        );

        if ($validator->fails()) {
            throw new ValidationException($validator);
        }

        try {
            if ($ownLocation) {
                $wizard = $this->updateWizard($location->hash, $request->all());
            } else {
                $wizard = $this->locationImportService
                    ->instantiateWizardFromLocation($locationArray)
                    ->mergeNewData($request->all());
            }

            $wizardService = new WizardService($wizard);
            $requestData = $wizardService->getFormattedRequestDataArray(
                $location->business_id,
                $location->hash,
                $redirectFromHash
            );

            // admin can edit any location
            if (!$ownLocation) {
                $requestData['external_provider_id'] = $location->location_version->external_provider_id ?? null;
                $requestData['source'] = $location->source;
                $requestData['country_code'] = $location->country_code;
                $requestData['publish_now'] = true;
                unset($requestData['user_id']);
            }

            $newLocation = $wizardService->addNewLocation($requestData, (bool)$ownLocation);
        } catch (Exception $e) {
            Honeybadger::notify($e, $request);
            Log::error($e);
            $genericError = 'There was an error during the saving process, please try again or contact us for support.';

            if ($e->getCode() === Response::HTTP_UNPROCESSABLE_ENTITY) {
                $error = json_decode($e->getMessage(), true);
                flash($error['message'][0] ?? $error['message'] ?? $e->getMessage() ?? $genericError)->error();
                return back();
            }

            throw new HttpException(Response::HTTP_UNPROCESSABLE_ENTITY, $genericError);
        }

        if ($newLocation ?? false) {
            $isEditAllRoute = back()->getTargetUrl() === route('admin.locations.edit', $location->hash);
            $routeNamePart = $isEditAllRoute ? 'edit' : ($request->has('step2') ? 'address' : 'hours');

resources/views/admin/locations/index/header.blade.php
<div class="card-header border-0 py-5">
    <h3 class="card-title align-items-start flex-column">
        <span class="card-label font-weight-bolder text-dark">{{ $businessName }}</span>
        <span class="text-muted mt-3 font-weight-bold font-size-sm">
            @lang('dashboard.listings.here_you_can_manage_and_update_your_business_listings', ['business_name' => $businessName])
        </span>
    </h3>
    <div class="card-toolbar">
        @if(Auth::user()->canAccessBusiness($locations[0]->business_id))
            <a href="{{ route('admin.businesses.edit', ['business' => $locations[0]->business_id]) }}" class="btn btn-success font-weight-bolder font-size-sm">
                <span class="svg-icon svg-icon-md svg-icon-white">@include('admin._includes.svg.edit-business')</span>@lang('dashboard.edit_business')
            </a>
        @endif
        <a href="{{ route('admin.location-wizard.add-location',[
                        'business_id' => $locations[0]->business_id,
                        'business_name' => $businessName,
                    ]) }}"
           class="btn btn-success font-weight-bolder font-size-sm mx-3">
            <span class="svg-icon svg-icon-md svg-icon-white">@include('admin._includes.svg.add-listing')</span>@lang('dashboard.listings.add_listing')
        </a>
    </div>
</div>

resources/views/admin/locations/index/table-row.blade.php
<tr>
    <td class="pl-0 py-7">
        <label class="checkbox checkbox-lg checkbox-inline {{ auth()->user()->getSubscriptionForLocation($location->hash) ? 'checkbox-disabled ' : '' }}">
            <input type="checkbox" value="1" class="select-location" data-hash="{{ $location->hash }}" {{ auth()->user()->getSubscriptionForLocation($location->hash) ? 'disabled="disabled"' : '' }}">
            <span></span>
        </label>
    </td>
    <td class="pl-0">
        <span class="text-dark-75 mb-1 font-size-lg">{{ optional($location->address)->full_address }}</span>
    </td>
    <td>
        <span class="text-dark-75 d-block font-size-lg">{{ optional(\Carbon\Carbon::parse($location->updated_at))->format('d/m/Y') }}</span>
    </td>
    @if($location->source !== \App\Models\Location::SOURCE_YEXT)
        <td class="text-center">
            <a href="{{ route('admin.locations.hours', $location->hash) }}" class="text-dark-75 text-hover-primary font-size-lg d-inline-block" target="_blank">
            <span class="btn btn-icon btn-light btn-hover-primary btn-sm">
                <span class="svg-icon svg-icon-primary svg-icon-2x">
                    @include('admin._includes.svg.hours')
                </span>
            </span>
            </a>
        </td>
        <td class="text-center">
            <a href="{{ route('admin.locations.address', $location->hash) }}" class="text-dark-75 text-hover-primary font-size-lg d-inline-block" target="_blank">
            <span class="btn btn-icon btn-light btn-hover-primary btn-sm">
                <span class="svg-icon svg-icon-primary svg-icon-2x">
                    @include('admin._includes.svg.address')
                </span>
            </span>
            </a>
        </td>
        <td class="text-center">
            <a href="{{ route('admin.locations.images', $location->hash) }}" class="text-dark-75 text-hover-primary font-size-lg d-inline-block" target="_blank">
            <span class="btn btn-icon btn-light btn-hover-primary btn-sm">
                <span class="svg-icon svg-icon-primary svg-icon-2x">
                    @include('admin._includes.svg.images')
                </span>
            </span>
            </a>
        </td>
        @unless(auth()->user()->canAccessBusiness($location->business_id) && count($locations) === 1)
            <td class="text-center">
                <a href="{{ route('admin.locations.texts', $location->hash) }}" class="text-dark-75 text-hover-primary font-size-lg d-inline-block" target="_blank">
            <span class="btn btn-icon btn-light btn-hover-primary btn-sm">
                <span class="svg-icon svg-icon-primary svg-icon-2x">
                    @include('admin._includes.svg.texts')
                </span>
            </span>
                </a>
            </td>
        @endunless
        <td class="text-center">
            <a href="{{ route('admin.locations.destroy', $location->hash) }}" class="ajax-delete text-dark-75 text-hover-primary font-size-lg d-inline-block"
               data-modal-title="{{ __('dashboard.delete_modal_title') }}"
               data-modal-cancel="{{ __('wizard.step3.cancel_btn') }}"
               data-modal-yes="{{ __('dashboard.yes_btn') }}"
            >
            <span class="btn btn-icon btn-light btn-hover-primary btn-sm">
                <span class="svg-icon svg-icon-primary svg-icon-2x">
                    @include('admin._includes.svg.trash')
                </span>
            </span>
            </a>
        </td>
    @else
        <td colspan="5" style="max-width:350px">
            <i class="mr-2 fa fa-info-circle" style="color: #3699ff;" aria-hidden="true"></i>@lang('dashboard.listings.listing_managed_by_yext_cannot_be_updated_here', [
            'yext_link' => '<a href="'.config('services.yext.login_url.'.config('app.locale')).'" target="_blank">Yext</a>'
            ]
        )
        </td>
    @endif
    <td class="text-center">
        @if(!auth()->user()->getSubscriptionForLocation($location->hash))
            <a href="{{ route('admin.promotions', ['hash' => $location->hash]) }}" class="text-dark-75 text-hover-primary font-size-lg d-inline-block" target="_blank">
            <span class="btn btn-icon btn-light btn-hover-primary btn-sm">
                <i class="fas fa-lg fa-sort-amount-up-alt" style="color: #3699ff;"></i>
            </span>
            </a>
        @else
            <span class="btn btn-icon btn-sm mt-1" style="cursor:default;">
                <i class="fas fa-medal fa-lg" style="color:gold;"></i>
            </span>
        @endif
    </td>
</tr>

resources/views/admin/locations/index/table.blade.php
<table class="table shadow-none table-head-custom table-vertical-center" id="kt_advance_table_widget_3">
    <thead>
    <tr class="text-left text-uppercase">
        <th class="pl-0" style="width: 20px">
            <label class="checkbox checkbox-lg checkbox-inline mr-2">
                <input type="checkbox" class="select-all-locations" value="1">
                <span></span>
            </label>
        </th>
        <th style="width:50%">@lang('dashboard.address')</th>
        <th>@lang('dashboard.edited')</th>
        <th style="width: 70px;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;@lang('dashboard.hours')&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</th>
        <th style="width: 70px;">@lang('dashboard.address')</th>
        <th style="width: 70px;">@lang('dashboard.images')</th>

        @unless(auth()->user()->canAccessBusiness($locations[0]->business_id) && count($locations) === 1)
            <th style="width: 70px;">@lang('dashboard.texts')</th>
        @endunless

        <th style="width: 70px;">@lang('dashboard.delete')</th>
        <th style="width: 70px;">@lang('dashboard.promote')</th>
    </tr>
    </thead>
    <tbody>
    @foreach($locations as $location)
        @include('admin.locations.index.table-row', ['location' => $location])
    @endforeach
    </tbody>
</table>